TINC_ETCD_NODES: https://etcd-host:2379
TINC_ETCD_KEY_DIR: /_osixia.net/tinc/

TINC_ETCD_KEY_TTL: 60 # in seconds
TINC_ETCD_KEY_UPDATE_INTERVAL: 45 # in seconds

TINC_ETCD_CLIENT_CA_FILENAME:
TINC_ETCD_CLIENT_CERT_FILENAME:
TINC_ETCD_CLIENT_KEY_FILENAME:
